import Head from 'next/head'
import LoginComponent from '@/components/Login/LoginComponent'
import SignUpComponent from '@/components/SignUP/SignUpComponent'
import Navupbar from '@/components/NavBar/navupbar'
import MainHome from '@/components/Home/MainHome'


export default function Home() {
  return (
    <>
      <Head>
        <title>Tennischool</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navupbar />
      <MainHome />
    </>
  )
}
